export const feedbackMatrix = {
    "IR_A": "I dette forløb ser det ud til, at fokus er på at træne korrekte svar, og teknologien bruges mest til at uddele materialet. Er det et bevidst valg at holde forløbet lærerstyret, eller kunne teknologien måske invitere eleverne lidt mere på banen?",
    "IR_B": "Det ser ud til, at eleverne skal producere noget, men rammerne er meget faste. Hvad ville der ske med læringen, hvis eleverne ikke fik en færdig skabelon, de skulle følge?",
    "IR_C": "Her er en spændende kontrast: Du bruger en meget åben teknologi, men selve opgaven lægger op til genkendelse og reproduktion. Kan eleverne bruge teknologiens åbenhed til at eksperimentere lidt mere?",
    "IR_D": "I dette analoge forløb ser det ud til, at fokus er på at huske og forstå eksisterende viden. Tænk over, om fraværet af teknologi gør det lettere eller sværere for eleverne selv at tage ejerskab over stoffet.",
    "AT_A": "Du lægger stærkt op til kritisk tænkning og analyse, men teknologien bruges mest som en digital opslagstavle. Kunne man bruge digitale værktøjer til selve kildeanalysen, f.eks. ved at lade eleverne dekonstruere en video eller en hjemmeside?",
    "AT_B": "Eleverne trænes i at tænke kritisk og bruger teknologien til at skabe deres løsninger. Det er en rigtig fin kombination! Overvej om det digitale værktøj i sig selv begrænser eller understøtter deres kritiske blik.",
    "AT_C": "Dette er et stærkt og sammenhængende design! Du inviterer til kritisk analyse, og teknologien står som et åbent rum, der understøtter deres selvstændige undersøgelse. Vær opmærksom på, om de har brug for stilladsering for ikke at fare vild.",
    "AT_D": "Her er der tale om god, klassisk kritisk tænkning uden skærme. Eleverne skal vurdere og analysere. Analoge redskaber som post-its, whiteboards eller bare en god samtale fungerer fremragende til dette formål.",
    "SA_A": "Eleverne ser ud til at være i gang med et kreativt arbejde, men uden at møde ægte faglig modstand undervejs. Samtidig bruges teknologien mest til at levere instruktioner. Pas på, at det ikke bare bliver hyggeligt 'pleaser-arbejde'.",
    "SA_B": "Dette ligner et klassisk 'skolescenarie': Eleverne producerer noget flot (f.eks. en præsentation), men både metode og indhold er givet på forhånd. Er der plads til, at de faktisk kan overraske dig med deres faglige valg?",
    "SA_C": "Der er en risiko her: Teknologien signalerer uendelige muligheder, men opgaven lader dem ikke træffe de svære faglige valg. Hvordan kan du introducere ægte 'faglig modstand' i deres proces, så det ikke kun handler om æstetik?",
    "SA_D": "I er i det analoge rum, og eleverne er beskæftigede – måske endda i flow – men tænk over, om aktiviteten reelt udfordrer deres faglige forståelse, eller om det mest er uforpligtende rutinearbejde.",
    "TB_A": "Du åbner op for en fantastisk undersøgende proces, hvor eleverne selv skal skabe ny viden! Men teknologien fungerer kun som en PDF-læser. Giv gerne eleverne digitale værktøjer, der lader dem forme og bygge deres egne svar.",
    "TB_B": "Forløbet kræver, at eleverne undersøger og skaber løsninger fra bunden, og de har et produktionsredskab til rådighed. Sørg blot for, at softwaren ikke låser dem fast i faste skabeloner, når nu din didaktik er så befriende åben.",
    "TB_C": "Det helt store og åbne værksted! Eleverne står med et uløst problem og et åbent digitalt materiale, de kan forme (f.eks. kodning eller podcast). Det er utrolig stærkt, men kræver meget af dig som lærer at guide dem gennem frustrationerne.",
    "TB_D": "Et intenst og åbent analogt forløb. Eleverne skaber ny viden uden at have facit på forhånd, udelukkende med fysiske materialer og eksperimenter. Gør brug af rummet og materialiteten til at skabe den nødvendige faglige modstand."
};
